### ISSUE TITLE
Determine how to efficiently index Beacon State with proof

### ISSUE THREAD

**Issue by dboreham** [cerc-io/ipld-eth-beacon-indexer#77]
Beacon state is a 60MB structured record that significantly changes every slot (12 seconds). If we want to represent this historical state in a hash-linked form, similar to our approach with ipld-eth, we need to be able to split the SSZ tree into changed and non-changed components that have their own hashes, then store the resulting pieces in a way that allows them to be found for a given block height, and also stitched together again to make a whole Beacon State record.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/ipld-eth-beacon-indexer/issues/77
