### ISSUE TITLE
Document that beacon "stuff" is required to generate standalone proofs

### ISSUE THREAD

**Issue by zramsay** [cerc-io/ipld-eth-beacon-indexer#88]
from Slack: "Also, if people want to generate stand alone proofs, they’ll need the beacon chain stuff"

**Comment by i-norden** [comment]
I dont think this is where we would document this. A proof from some execution layer data up to a beacon chain root spans the functionality of multiple repos, and doesn't make much sense within the context of the beacon chain objects/db in isolation.
