### ISSUE TITLE
Dockerfile tweak to build on ARM

### ISSUE THREAD

**Issue by iskay** [cerc-io/ipld-eth-beacon-indexer#89]
The dockerfile uses `frolvlad/alpine-bash:latest` which doesn't have an ARM image on Docker hub, so the build fails on ARM. If we use
```
FROM alpine:latest
RUN apk --no-cache add ca-certificates libstdc++ busybox-extras gettext libintl bash gawk sed grep bc coreutils
```
instead, the ARM build works.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/ipld-eth-beacon-indexer/issues/89
